### ISSUE TITLE
Add AppVeyor build for running the tests

### ISSUE THREAD

**Issue by mrbean-bremen** [vvvv/SVG#378]
To make regressions less likely, it makes sense to automatically run the tests for PRs and make passing tests a merge condition. 
I propose the following steps:
- [x] Add SVG to AppVeyor (has to be done by the maintainer)
- [x] Add an appveyor.yml config file that allows running the unit tests (done in #375, with [this result](https://ci.appveyor.com/project/mrbean-bremen/svg/builds/20517572/tests))
- [x] Add an image comparison test that make automatic comparisons between SVG and reference PNG (with some tolerance, probably configurable for different images) (partly done in #380)
- [x] Add as many of the existing images (from W3C test suite and from regression tests) to that test (partly done in #380, W3C tests only)

What do you think?

**Comment by tebjan** [comment]
hi @mrbean-bremen what do you need me to do regarding appveyor? i could also add you as a collaborator so you can change the necessary settings yourself.

**Comment by mrbean-bremen** [comment]
Hi @tebjan, I think you have to do this yourself - I'm a collaborator in another project and couldn't do it there neither. 
Basically, you have to sign-in into AppVeyor using your GitHub account and add your repository. You will be asked to give it OAuth read access, if I remember correctly. Once you did this, each check-in in master or a PR will trigger a build.

**Comment by mrbean-bremen** [comment]
Thinking about your collaboration offer: what I could do - in case you are interested - is going through the existing issues (and maybe PRs), close the ones that are fixed or have insufficient information to work on, and classify the rest to get a better picture what remains to do.

**Comment by tebjan** [comment]
that would be a tremendous help!

**Comment by mrbean-bremen** [comment]
Glad to be able to help! Though I can't promise anything regarding the time line. My free time that I can use for this is varying...

**Comment by tebjan** [comment]
sure, as your time allows, any help is welcome. if you need anything or if you think you can't continue for a longer time period, let me know.

**Comment by mrbean-bremen** [comment]
Is it ok for me to merge PRs that are clear enough to have no side effects (in my opinion, obviously...)?
I won't merge my own PRs, of course...

**Comment by tebjan** [comment]
yes, go ahead. you can also merge your own if you tested them. i would also start to use a develop branch and only merge to master for new nuget packages.

**Comment by mrbean-bremen** [comment]
ok, I will merge some of the small PRs - the ones I just approved.

**Comment by mrbean-bremen** [comment]
@tebjan - a couple of questions for you:
- I'm now almost done with the PRs; there is the Netstandard20 support PR which I want to merge if possible, but I want to know your plans for the next Nuget release first (e.g. shall it be included or not)
- there is the skiasharp project to be considered - if you are planning to switch there, this may change the priorities
- it would be nice if you could enable AppVeyor support to easier check for regressions (and if you have an idea for a better image comparison algorithm, let me know :)
- a minor thing - I would like to use a consistent formatting (always spaces instead of tabs if possible), as with the current mixup the code and especially the diffs are often garbled, would that be ok for you?

I will continue to check the existing issues as time permits (and hopefully close a few more), and maybe try to fix a few if I am done with that. Let me know if you need something else, or have other priorities.

**Comment by tebjan** [comment]
added appveyor

**Comment by mrbean-bremen** [comment]
This basically works now, so I'm closing this (someone may come up with a better image comparison algorithm later).
@tebjan - I'm done with the PR merges, but there is one regression I know of (and cannot reproduce - see #384), that I would like to handle before a nuget release.
